### ISSUE TITLE
При просмотре в Safari for Windows нет белого блока вверху страницы

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#10]
При просмотре главной страницы в Safari for Windows нет белого блока вверху страницы. Подробности на видео.
https://youtu.be/z6z1dQVNNqk

**Comment by VitalyBesk** [comment]
какая версия сафари?
У меня в сафари работает все

**Comment by zukitu** [comment]
У меня 5.1.4

**Comment by VitalyBesk** [comment]
Я только что скачал 5.1.4 меню в header как и в хроме отображается, не знаю что там у тебя не так. Они на одном движке с хромом

**Comment by zukitu** [comment]
Странно.
Переустановила сафари, закрыла всё кроме сафари, всё равно вот так ведет себя главная.

**Comment by zukitu** [comment]
На самом деле, не знаю ни кого, кто бы пользовался Сафари на Windows, так что, может, это и не важно.

**Comment by VitalyBesk** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/15989398/15261265/10d2e464-1964-11e6-8355-47110d164e09.png)
Вот так у меня. 
Safari на Apple юзать надо, а не на винде

**Comment by zukitu** [comment]
Ну, у меня эппла нет. Хорошо, я закрываю.
