### ISSUE TITLE
Фиксированная белая шапка становится прозрачной на 0.5 секунды

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#11]
Если кликнуть на иконку facebook в разделе команда, перейти на страницу facebook, дождаться её загрузки, а потом вернуться назад на сайт с помощью кнопки в браузере "назад",   фиксированная белая шапка становится прозрачной на 0.5 секунды, затем снова становится белой.
Проявляется в Chrome и Internet Explorer, в  Firefox такого эффекта нет.

**Comment by zukitu** [comment]
На видео демонстрация в таком порядке: Chrome/Firefox/IE
https://www.youtube.com/watch?v=r6C6e6jL2Ko&feature=youtu.be

**Comment by zukitu** [comment]
Эффект проявляется при переходе по любой ссылке, не только Facebook.

**Comment by VitalyBesk** [comment]
Это эффект плавного перехода в css, а не баг, transition 0.5s ease-out если не ошибаюсь. Это дело вкуса.

**Comment by zukitu** [comment]
Согласна, насчёт вкуса. Ну, это из серии "баги по заказам". Таня попросила добавить это в баги.

**Comment by VitalyBesk** [comment]
Done

**Comment by zukitu** [comment]
Закрываю.
