### ISSUE TITLE
На главной странице в блоке "Портфолио" нет кнопок-стрелок

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#12]
На главной странице в блоке "Портфолио" нет кнопок-стрелок для навигации между элементами портфолио.
![default](https://cloud.githubusercontent.com/assets/18324216/15274682/4ff6ab36-1ac1-11e6-970c-fdfd286b8981.jpg)

**Comment by VitalyBesk** [comment]
Done

**Comment by zukitu** [comment]
Я вижу что портфолио теперь выглядит совсем по-другому, но стрелок нет.

**Comment by VitalyBesk** [comment]
Должно быть так
![screenshot_2](https://cloud.githubusercontent.com/assets/15989398/15417629/bc43026a-1e60-11e6-8829-270ba72788e0.png)

**Comment by VitalyBesk** [comment]
ты обновляла npm? Потому что в node_modules новая зависимость

**Comment by zukitu** [comment]
Npm обновляла вчера, может просто перезагрузка нужна была.
Теперь вижу. Красота) 
Закрываю.
