### ISSUE TITLE
<title> Главной страницы "webex.kiev.ua — Ещё один сайт на WordPress"

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#13]
<title> Главной страницы "webex.kiev.ua — Ещё один сайт на WordPress"
Какая прекрасная реклама.
![default](https://cloud.githubusercontent.com/assets/18324216/15274708/14faeab4-1ac2-11e6-81c1-7aabb76e035a.jpg)

**Comment by VitalyBesk** [comment]
Я не занимаюсь WP, но за вывод заголовка отвечает функция wp_title, а названия заголовка страницы желательно в WP с админки править.

**Comment by VitalyBesk** [comment]
Done
