### ISSUE TITLE
Расположение навигационных кнопок-кружков в портфолио не соответствует макету

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#14]
Кружки должны быть между изображением и кнопкой "БОЛЬШЕ ПРОЕКТОВ"
![default](https://cloud.githubusercontent.com/assets/18324216/15274780/a7f99ef4-1ac3-11e6-89db-604ca8792b4c.jpg)

**Comment by VitalyBesk** [comment]
Ну да, оно и не будет соотвествовать вместе со стрелками, так как использовался слайдер swiper.js со всеми зависимостями, попробую на slick.js  заменить.
