### ISSUE TITLE
Изображение в блоке "Портфолио" выходит за пределы блока.

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#15]
Изображение в блоке "Портфолио" выходит за пределы блока.
![portfolio](https://cloud.githubusercontent.com/assets/18324216/15292363/79d8d5f8-1b8b-11e6-998e-b65ded5e8b53.jpg)

**Comment by VitalyBesk** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/15989398/15369643/32e6c24c-1d3c-11e6-888c-ba71f5addd51.png)
Инспектор хрома не согласен) 
Max-width:100%;

**Comment by VitalyBesk** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/15989398/15370047/d42a8c82-1d3d-11e6-821b-517d46894cff.png)
![screenshot_14](https://cloud.githubusercontent.com/assets/15989398/15370048/d42d7e06-1d3d-11e6-95be-a94ddf2b8a2f.png)
![screenshot_15](https://cloud.githubusercontent.com/assets/15989398/15370049/d4307124-1d3d-11e6-8307-2c683c67292e.png)

**Comment by zukitu** [comment]
У меня изображение  выходит за пределы при масштабе 100%. При увеличении\уменьшении баг пропадает, изображение становится вровень с блоком.

**Comment by zukitu** [comment]
При масштабе в 33% и 67% тоже проявляется.
https://youtu.be/thbDs3wB_1k

**Comment by VitalyBesk** [comment]
Это отрисовка в браузере и динамическое вычисление ширины. На это повлиять  я не могу.

**Comment by zukitu** [comment]
Ладно, я это закрываю, будем считать что это не наш баг, а браузера.
