### ISSUE TITLE
Стрелка "вверх" на главной странице находится ниже, чем должна..

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#16]
Стрелка должна быть наполовину в футере, наполовину в основном блоке. Прикладываю скриншот с замечаниями Андрея.
![-2](https://cloud.githubusercontent.com/assets/18324216/15377071/b3c8f270-1d61-11e6-9efe-1c46b1b8ecdb.jpg)

**Comment by VitalyBesk** [comment]
Done

**Comment by zukitu** [comment]
Закрываю.
