### ISSUE TITLE
Текст на главной странице не соответствует макету.

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#17]
![text](https://cloud.githubusercontent.com/assets/18324216/15377846/601e44b2-1d67-11e6-9334-e226e2e74997.jpg)
Текст на главной странице в блоке "Из чего состоит стоимость сайта" не соответствует макету.
Текст, который сейчас: "Качественный сайт - это работа профессионалов, которые вкладывают в сайт свое драгоценное время"
Текст из макета: "Качественный сайт - это работа профессионалов, которые вкладывают в разработку продукта весь свой профессионализм и драгоценное время".

Текст в блоке "Услуги и цены" тоже расходится с текстом из макета, хотя мне больше нравится тот который сейчас на главной: "За разработку адаптивной и мобильной версии +30% к цене"
В макете: "за разработку адаптивного и мобильного сайта +30% к стоимости"

**Comment by VitalyBesk** [comment]
Какой внимательный у тебя глаз)

**Comment by VitalyBesk** [comment]
Done
