### ISSUE TITLE
Неправильное описание услуг на странице "Наши услуги"

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#18]
На странице "Наши услуги" описание категорий "Корпоративный сайт", "Сайт-каталог", "Интернет-магазин" идентичное описанию "Лендинг-пейдж":
Одностраничный сайт
Панель управления
Индивидуальный дизайн
Домен и хостинг в подарок

Должно отличаться хотя бы в первой строчке, интернет-магазин, явно многостраничный сайт.
А в макете все категории, кроме лендинг-пейдж указаны как "Многостраничный сайт"
![default](https://cloud.githubusercontent.com/assets/18324216/15392008/3926a15e-1dcd-11e6-8a53-bec38a1edaae.jpg)
"

**Comment by VitalyBesk** [comment]
Напиши об этом Андрею, текст не я пишу)

**Comment by zukitu** [comment]
Хорошо, переназначаю на Андрея.

**Comment by andriishtyka** [comment]
Изначально весь копирайт драфтовый был. Поетому все схожее по услугам

**Comment by andriishtyka** [comment]
Ксли есть предложения напишите мне

**Comment by zukitu** [comment]
Закрываю.
