### ISSUE TITLE
На странице «Все проекты» нет примеров в категориях «сайт-каталог» и «интернет-магазин»

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#2]
На странице «Все проекты» нет примеров в категориях «сайт-каталог» и «интернет-магазин». Если их нет совсем, возможно стоит туда поместить какой-то текст или изображение из серии «как бы это могло выглядеть».

**Comment by VitalyBesk** [comment]
Возможно сделаем для интернет магазина и сайта каталога ссылки неактивными. Дизайнер еще не решил.

**Comment by VitalyBesk** [comment]
И Это)

**Comment by zukitu** [comment]
Закрываю.
