### ISSUE TITLE
Страница пректа ForexPro, не относится ни к одной категории

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#3]
На странице «Все проекты» в разделе «Все проекты» есть страница ForexPro, которой нет ни в одной категории, если смотреть не все проекты, а по категориям

**Comment by VitalyBesk** [comment]
Интересное замечание, мы учтем.

**Comment by VitalyBesk** [comment]
Это тоже закрой)

**Comment by zukitu** [comment]
Нет категорий, нет проблемы)
