### ISSUE TITLE
Невидимый email в контактах на главной странице

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#6]
На главной странице в блоке «Контакты» электронная почта скрыта и отображается только если на нее навести курсор.

**Comment by VitalyBesk** [comment]
Можно скрин, что там не видно?

**Comment by zukitu** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/18324216/14927625/bdda566a-0e5b-11e6-9f4f-0acc76759ae5.png)
Почта появляется только при наведении на неё курсора.

**Comment by VitalyBesk** [comment]
Хм,у меня везде видно на всех браузерах. Надо разбираться

**Comment by zukitu** [comment]
Я сейчас еще раз перепроверю.

**Comment by VitalyBesk** [comment]
Профиксил.

**Comment by zukitu** [comment]
Работает, всё видно.
