### ISSUE TITLE
Ссылки "Перейти на сайт "на страницах проектов не ведут на сайты проектов.

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#7]
На страницах poject-page, project-page2, project-page3, project-page4 кнопка «перейти на сайт» ведёт на эту же страницу, а не на сайт проекта

**Comment by VitalyBesk** [comment]
Я ссылки еще не добавлял.

**Comment by zukitu** [comment]
Вижу что ссылки заработали, закрываю.
