### ISSUE TITLE
Не отображается "close-menu.png" на странице ForexPro

### ISSUE THREAD

**Issue by zukitu** [webexkievstudio/home#9]
На странице проекта ForexPro при просмотре с мобильного устройства изображение кнопки "закрыть меню" не отображается, потому что на него дана неправильная ссылка. Изображение находится в папке "icons", а для этой страницы указана ссылка на папку "common".
![screenshot_3](https://cloud.githubusercontent.com/assets/18324216/14930007/6e7ff256-0e69-11e6-8268-04aa6ff802e4.png)

**Comment by VitalyBesk** [comment]
закрывай, исправил
